name: Release Fix Flow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  run-type-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run type checks
      run: npm run type-check

    - name: Run tests
      run: npm test

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Yandex Container Registry
      run: |
        echo "${{ secrets.YANDEX_CLOUD_SA_KEY }}" | docker login -u json_key --password-stdin cr.yandex

    - name: Build and push Docker image
      run: |
        docker build -t cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} .
        docker tag cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
        docker push cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
        docker push cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest

  create-release-fix-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create GitHub tag for release fix
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -b releases/${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
        git push origin releases/${{ github.event.inputs.release_version }}_fix${{ github.run_number }}

  add-comment-to-issue:
    runs-on: ubuntu-latest
    needs: [run-type-checks-and-tests, build-and-push-docker-image, create-release-fix-tag]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get previous release tag
      id: get-previous-tag
      run: echo "::set-output name=prev-tag::$(git describe --tags --abbrev=0 HEAD^)"

    - name: Get list of commits
      id: get-commits
      run: echo "::set-output name=commits::$(git log --pretty=format:"%h - %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD)"

    - name: Create GitHub Issue comment
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: issues } = await github.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
          });
          const issueNumber = issues.find(issue => issue.title.startsWith(`Release ${{ github.event.inputs.release_version }}`)).number;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: `### Release Fix Information
- **Date**: $(date +%Y-%m-%d)
- **Author**: ${{ github.actor }}
- **Commits**:
${{ steps.get-commits.outputs.commits }}
- **Docker image**: [cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}](https://cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }})`
