name: Release Fix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  run-type-checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run type checks
        run: npm run type-check

      - name: Run tests
        run: npm test

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Container Registry
        run: echo ${{ secrets.YANDEX_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} .
          docker tag cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} cr.yandex/${{ secrets.YANÐ”EX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
          docker push cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          docker push cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest

  create-release-fix-tag:
    runs-on: ubuntu-latest
    needs: [run-type-checks-and-tests, build-and-push-docker-image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub tag for release fix
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b releases/${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          git tag ${github.event.inputs.release_version}_fix${{ github.run_number }}
          git push origin releases/${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          git push origin ${github.event.inputs.release_version}_fix${{ github.run_number }}

  add-comment-to-issue:
    runs-on: ubuntu-latest
    needs: [create-release-fix-tag]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get previous release tag
        id: get-previous-tag
        run: echo "PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_ENV

      - name: Get list of commits
        id: get-commits
        run: |
          if [ -n "${{ env.PREV_TAG }}" ]; then
            echo "COMMITS=$(git log --pretty=format:'%h - %s' ${{ env.PREV_TAG }}..HEAD)" >> $GITHUB_ENV
          else
            echo "COMMITS=$(git log --pretty=format:'%h - %s' HEAD)" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            const issueNumber = issues.find(issue => issue.title.startsWith(`Release ${github.event.inputs.release_version}`)).number;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `### Release Fix Information
- **Date**: $(date +%Y-%m-%d)
- **Author**: ${github.actor}
- **Commits**:
${{ env.COMMITS }}
- **Docker image**: [cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}](https://cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }})`
